### ISSUE TITLE
Answers and answer's comments are not displayed in the group activity

### ISSUE THREAD

**Issue by oseg** [ColdTrick/questions#14]
Title: Answers and answer's comments are not displayed in the group activity

Context: elgg v2.3.3 and questions v5.1 activated

Scenario:
- Enable "questions" tool in a group
- Create a question in this group
- Add an answer to this question
- Add a comment to this answer
- Have a look at this group activity
-> The question is displayed but not the answer and not the answer's comment
- Have a look at the whole site activity
-> The question, the answer and the answer's comment are displayed

**Comment by jeabakker** [comment]
i fixed the issue for the answers, but couldn't fix it for the comments

**Comment by jeabakker** [comment]
this is due to how questions -> answers -> comments are linked
