### ISSUE TITLE
"Search in this group" does not search in group question's answers

### ISSUE THREAD

**Issue by oseg** [ColdTrick/questions#15]
Context: elgg v2.3.3+questions v5.2

Scenario:

- Create a group
- In this group, create a question with "comala" in the title and details fields
- in this question's page, add an answer containing "comala"
- go to the group profile page
- in the "search in this group" field, enter "comala" and press "go" button
- -> the "comala" question is found but not the "comala" answer
- in the right menu, click "All" link
- -> Both the "comala" question and its "comala" answer are found

May be related to "'Search in this group' does not search in group comments" elgg issue: https://github.com/Elgg/Elgg/issues/11172

**Comment by jeabakker** [comment]
correct because of the structure of answers they cant be found

**Comment by jdalsem** [comment]
Closing this as Elgg/Elgg#11172 is the main reason this is not working. I do not see a workaround at this moment.
