### ISSUE TITLE
"No longer correct" link is not working, the answer remains "correct" and question remains "locked"

### ISSUE THREAD

**Issue by oseg** [ColdTrick/questions#16]
Plugins context: elgg v2.3.3 + question plugin v5.2

Settings context: "Close a question when it gets a marked answer" question setting is set to "yes"

Scenario:
- Create a group and enable "questions" in this group
- Create a question
- Add an answer to this question
- Click on the "correct" link to mark the answer as "correct"
-> The answer is marked as "correct" and the question is locked
- Click on the "No longer correct" link
-> The answer remains marked as correct and the question remains locked

The answer should be unmarked as "correct" and the question should be unlocked

**Comment by jeabakker** [comment]
I'm unable to reproduce this issue. Could you give me some more information:

- what are the expert settings
- what kind of user is clicking on the links (group owner, expert, question owner, site admin)

**Comment by oseg** [comment]
Expert settings are disabled:
- Enable expert roles: No
- Only experts can answer a question: No
- Only experts can mark an answer as the correct answer: No

The user clicking on the link is the question owner. He is not an expert, not the group owner, not a group admin and not a site admin.

Hope it helps

**Comment by jeabakker** [comment]
thanks no i can reproduce it
