### ISSUE TITLE
Strange thing with tabs

### ISSUE THREAD

**Issue by dragonjon** [ColdTrick/questions#18]
Hi @jeabakker I'm testing questions to implement it in production, when I access the general questions there are four different tabs:
Todo =/questions/all ---Ok 
Mine=/questions/owner/USER ---OK
Todo=/questions/todo ?? what is it
Experts=/questions/experts ---OK

and in the groups:
Todo =/questions/group/90/all ---OK  (90 is the  group number)
Todo=/questions/todo ?? what is it again
Group Todo=/questions/todo/90 no is the url where is going /questions/all
Experts=/questions/experts ---OK

and what to move to discussions is not in the edition of the question
![captura](https://user-images.githubusercontent.com/15904661/32788990-fc6488fe-c95a-11e7-90a7-d2bb915efc27.JPG)

Thanks for your work
Jon

**Comment by jeabakker** [comment]
The ToDo tabs are for Experts and list the questions that need an answer soon.
In the plugin settings you can set a default solution time, and in the group you can also set this. This indicates to the experts that they need to answer the question within that time. 

So for this functionality we added a list where the Experts can find a list of all the questions they need to help answer.

**Comment by jeabakker** [comment]
I recently pushed a fix that if experts ins't enabled the ToDo tabs don't get shown

**Comment by jdalsem** [comment]
See https://github.com/ColdTrick/questions/commit/7ee2f9df95a5046ff18752b37c805b52b8c0f77e
