### ISSUE TITLE
Form for adding answers don't show

### ISSUE THREAD

**Issue by RiverVanRain** [ColdTrick/questions#20]
This form is disappeared on the question view's page in v5.3 (for non-admins with the default plugin's settings).
After debugging I notice that this code (from [previous version](https://github.com/ColdTrick/questions/commit/05b9587ae1aa1975060d3cd6dcea60488c9c91d6#diff-e93c440af885a2ac30d2e08c774a3934L445)) is returns form again:

```
if (!($container instanceof ElggGroup)) {

  return !questions_limited_to_groups();

}
```

in function [questions_can_ask_question()](https://github.com/ColdTrick/questions/blob/master/lib/functions.php#L428) of [lib/functions.php](https://github.com/ColdTrick/questions/blob/master/lib/functions.php)

**Comment by jeabakker** [comment]
I'm unable to reproduce this. Both with user questions and a question in a group.

Could you provide me with steps to reproduce

**Comment by RiverVanRain** [comment]
User 1 adds a new Q:
![1_qa](https://user-images.githubusercontent.com/2176145/34273347-fc38fb5a-e6a4-11e7-937f-105b75311e90.png)

User 2 trying to answer but can not see a form for it:
![2_qa](https://user-images.githubusercontent.com/2176145/34273420-4f1e02ca-e6a5-11e7-999e-53e1ecc91f0c.png)

Admin can see but not a user.

No 3rd-party plugins installed.
I've tried it with the deactivated Groups -- no results.

The Questions' settings are:
![1_qa](https://user-images.githubusercontent.com/2176145/34273525-c2c71b30-e6a5-11e7-9b36-42c46c02e2ae.png)

Works with the above 'hack' only
