### ISSUE TITLE
1 Answers

### ISSUE THREAD

**Issue by javery86** [ColdTrick/questions#21]
Please update plugin so either it says "1 Answer" when there is only one, or maybe show the answers like this: 

Answers (1)

That would work for all scenarios.

**Comment by jeabakker** [comment]
It's show as 'Answers (1)' for over 2 years https://github.com/ColdTrick/questions/commit/2993f5d32aa563daa0b1b8a77f393d2251448664#diff-11df5a25fc4867e3f9a401afea98b152R73

Or can you show me a place where this is not the case

**Comment by javery86** [comment]
See here: <img width="957" alt="questions" src="https://user-images.githubusercontent.com/23128240/34307989-0045ceea-e6ef-11e7-93a9-09648e5cda80.png">

**Comment by javery86** [comment]
Why was this closed?

**Comment by jeabakker** [comment]
because i fixed it ;)
