### ISSUE TITLE
Search result crash if an unreachable container(the question) answer is found

### ISSUE THREAD

**Issue by oseg** [ColdTrick/questions#22]
Context: elgg v2.3.3 + question v5.4.1

Scenario:
- In an invisible group
- User A creates a question, with group access level
- User B answers to the question with 'keyword' in the answer
- User B leaves the invisible group
- User B search for 'keyword'
=> a crash happens with the following stack

PHP Fatal error:  Call to a member function getDisplayName() on boolean in C:\xampp\htdocs\cmt-1.3\mod\questions\views\default\search\object\answer\entity.php on line 48
PHP Stack trace:
PHP   1. {main}() C:\xampp\htdocs\cmt-1.3\index.php:0
PHP   2. Elgg\Application::index() C:\xampp\htdocs\cmt-1.3\index.php:8
PHP   3. Elgg\Application->run() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\classes\Elgg\Application.php:384
PHP   4. Elgg\Router->route() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\classes\Elgg\Application.php:436
PHP   5. call_user_func:{C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\classes\Elgg\Router.php:100}() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\classes\Elgg\Router.php:100
PHP   6. search_page_handler() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\classes\Elgg\Router.php:100
PHP   7. elgg_view_resource() C:\xampp\htdocs\cmt-1.3\mod\search\start.php:62
PHP   8. Elgg\ViewsService->renderView() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\lib\views.php:514
PHP   9. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  10. include() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  11. elgg_view() C:\xampp\htdocs\cmt-1.3\mod\search\views\default\resources\search\index.php:194
PHP  12. Elgg\ViewsService->renderView() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\lib\views.php:337
PHP  13. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  14. include() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370
PHP  15. elgg_view() C:\xampp\htdocs\cmt-1.3\mod\search\views\default\search\list.php:113
PHP  16. Elgg\ViewsService->renderView() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\lib\views.php:337
PHP  17. Elgg\ViewsService->renderViewFile() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:306
PHP  18. include() C:\xampp\htdocs\cmt-1.3\vendor\elgg\elgg\engine\classes\Elgg\ViewsService.php:370

**Comment by oseg** [comment]
There is a potential fix in https://github.com/ColdTrick/questions/pull/17

**Comment by jeabakker** [comment]
fixed by 82c5ea8de3c0908351fc2bca247f905e2d075214
