### ISSUE TITLE
Question owner is not notified on answer comments

### ISSUE THREAD

**Issue by oseg** [ColdTrick/questions#9]
Issue reproduced on both context:
- elgg v1.12.14 + questions v2.1.2 + content_subscription v3.1
- elgg v2.2.1 + questions v3 + content_subscription v4

Scenario:
- create 3 users (user1, user2 & user3) with both Settings/Notifications/Personal notifications checked (when actions are performed on your content & when comments get posted on content you subscribed to)
- create a "test-group", add the 3 users to the group and enable group notifications for the group users 
- user1 adds a group question
=> user2 & user3 are notified of the added question in the group
- user2 adds an answer to user1's question
=> user1 is notified of the answer
- user3 adds a comment on user2's answer
=> user2 is notified of the comment but user1 is NOT

The question owner (user1) should be notified of an answer's comment

**Comment by oseg** [comment]
Suggested fix in addQuestionOwnerToAnswerSubscribers() hook

Replace
```
$answer = $event->getObject();
if (!($answer instanceof \ElggAnswer)) {
    return;
}
$question = $answer->getContainerEntity();
```
by
```
$object = $event->getObject();
$container = $object->getContainerEntity();
if ($object instanceof \ElggAnswer) {
    $question = $container;
} else if ($container instanceof \ElggAnswer) {
    $question = $container->getContainerEntity();
} else {
    return;
}
```

**Comment by jeabakker** [comment]
thanks for reporting
